#!/bin/bash

# SPDX-FileCopyrightText: 2022 Melvin Keskin <melvo@olomono.de>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

#
# This script updates the list that contains XEP metadata used by "doap.xsl".
#
# It should be run before generating the Doxygen documentation.
#

# The list is generated by "https://github.com/xsf/xeps/blob/master/tools/extract-metadata.py".
SOURCE_URL="https://xmpp.org/extensions/xeplist.xml"

QXMPP_DOC=$(dirname "$(readlink -f "${0}")")
DESTINATION_PATH="${QXMPP_DOC}/xeplist.xml"

curl -L ${SOURCE_URL} > ${DESTINATION_PATH}
