/*
 * Copyright (C) 2008-2021 The QXmpp developers
 *
 * Author:
 *  Linus Jahn <lnj@kaidan.im>
 *  Melvin Keskin <melvo@olomono.de>
 *
 * Source:
 *  https://github.com/qxmpp-project/qxmpp
 *
 * This file is a part of QXmpp library.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 */

#include "QXmppMixManager.h"
#include "QXmppConstants_p.h"
#include "QXmppClient.h"
#include "QXmppDiscoveryIq.h"
#include "QXmppDiscoveryManager.h"
#include "QXmppMixInvitation.h"
#include "QXmppMixIq.h"
#include "QXmppMixItem.h"
#include "QXmppPubSubEvent.h"
#include "QXmppPubSubIq.h"
#include "QXmppPubSubItem.h"
#include "QXmppPubSubManager.h"
#include "QXmppRosterManager.h"
#include "QXmppUtils.h"

#include <QDomElement>
#include <QStringBuilder>

QString QXmppMixService::jid() const
{
    return m_jid;
}

void QXmppMixService::setJid(const QString &jid)
{
    m_jid = jid;
}

bool QXmppMixService::searchable() const
{
    return m_searchable;
}

void QXmppMixService::setSearchable(bool searchable)
{
    m_searchable = searchable;
}

bool QXmppMixService::canCreateChannel() const
{
    return m_canCreateChannel;
}

void QXmppMixService::setCanCreateChannel(bool canCreateChannel)
{
    m_canCreateChannel = canCreateChannel;
}

///
/// Returns true, if the given \c QXmppMixService equals the set one.
///
bool QXmppMixService::operator==(const QXmppMixService &other) const
{
    return m_jid == other.jid() && m_searchable == other.searchable() && m_canCreateChannel == other.canCreateChannel();
}

QXmppMixManager::QXmppMixManager() = default;

QStringList QXmppMixManager::discoveryFeatures() const
{
    return QStringList() << ns_mix;
}

QList<QXmppMixService> QXmppMixManager::services() const
{
    return m_services;
}

bool QXmppMixManager::isSupportedByServer() const
{
    return m_isSupportedByServer;
}

bool QXmppMixManager::isArchivingSupportedByServer() const
{
    return m_isArchivingSupportedByServer;
}

///
/// Creates a channel.
///
/// \param channelOrServiceJid JID of the MIX channel (e.g. "channel@mix.example.org") or only the JID of the MIX service (e.g. "mix.example.org") to create a channel with an ID generated by the server (e.g. "09eb3353-a414-4a41-99b9-c123824b1aea@mix.example.org")
/// \param isPublic true for creating a public group chat or false (default) for a private one; this parameter is not relevant if channelOrServiceJid consists only of the service JID because the channel being created then will not be publicly accessible anyway
///
void QXmppMixManager::createChannel(const QString &channelOrServiceJid, const bool isPublic)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(QXmppUtils::jidToDomain(channelOrServiceJid));
    iq.setActionType(QXmppMixIq::Create);
    iq.setChannelId(QXmppUtils::jidToUser(channelOrServiceJid));

    // Cache the request for a private channel to create the corresponding "Allowed" node after channel creation.
    // TODO: The current XEP seems to tend to not create an Allowed node if private without a channel ID by "if (!isPublic && !iq.channelId().isEmpty())"
    // but the problem is that everyone who knows the channel JID can join it at the moment because it cannot be "not addressable" as specified in the XEP or the question is what they mean by that
    if (!isPublic || iq.channelId().isEmpty())
        m_requestsBeingProcessed.insert(iq.id(), channelOrServiceJid);

    client()->sendPacket(iq);
}

///
/// Joins a channel to become a participant of it.
///
/// \param channelJid JID of the channel being joined
/// \param nick nickname of the user (by default, required by the server) or none if no nickname should be set
/// \param subscribeToMemberJids nothing or true for being informed about added and removed member JIDs, otherwise false
/// \param subscribeToBannedJids nothing or true for being informed about added and removed banned JIDs, otherwise false
/// \param subscribeToConfiguration nothing or true for being informed about configuration changes, otherwise false
/// \param subscribeToInformation nothing or true for being informed about information changes, otherwise false
/// \param subscribeToMessages nothing or true for receiving messages which were sent over the channel, otherwise false
/// \param subscribeToParticipants nothing or true for being informed about joined users and left participants, otherwise false
/// \param subscribeToPresences nothing or true for being informed about the participants' presences, otherwise false
///
void QXmppMixManager::joinChannel(const QString &channelJid, const QString &nick, const bool subscribeToMemberJids, const bool subscribeToBannedJids, const bool subscribeToConfiguration, const bool subscribeToInformation, const bool subscribeToMessages, const bool subscribeToParticipants, const bool subscribeToPresences)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(client()->configuration().jidBare());
    iq.setActionType(QXmppMixIq::ClientJoin);
    iq.setChannelJid(channelJid);

    if (!nick.isEmpty())
        iq.setNick(nick);

    QStringList nodesBeingSubscribed;

    if (subscribeToMemberJids)
        nodesBeingSubscribed.append(ns_mix_node_allowed);
    if (subscribeToBannedJids)
        nodesBeingSubscribed.append(ns_mix_node_banned);
    if (subscribeToConfiguration)
        nodesBeingSubscribed.append(ns_mix_node_config);
    if (subscribeToInformation)
        nodesBeingSubscribed.append(ns_mix_node_info);
    if (subscribeToMessages)
        nodesBeingSubscribed.append(ns_mix_node_messages);
    if (subscribeToParticipants)
        nodesBeingSubscribed.append(ns_mix_node_participants);
    if (subscribeToPresences)
        nodesBeingSubscribed.append(ns_mix_node_presence);

    iq.setNodesBeingSubscribed(nodesBeingSubscribed);

    // Cache the request to retrieve the channel JID for emitting  a corresponding signal.
    m_requestsBeingProcessed.insert(iq.id(), channelJid);

    client()->sendPacket(iq);
}

///
/// Invites a contact to a channel.
///
/// In case of a private channel, the contact's JID has to be added as a member via addMemberJid() before.
///
/// \param channelJid JID of the channel which the contact is invited to
/// \param inviteeJid JID of the invited contact
///
void QXmppMixManager::inviteContactToChannel(const QString &channelJid, const QString &contactJid)
{
    // TODO: Check if the user being invited and the server support MIX invitations
    // TODO: Use complete process of requesting an invitation from the server and forwarding it to the invitee

    // The case that an Allowed node already exists is not covered since the server responds with an error but it has no other known disadvantage.

    // TODO: Does an "Allowed" node exist for the passed channel JID?
    // If yes, request all items, check if an item with the passed user JID as ID is included and if not, publish an item for it.
    // In both cases, send an invitation to the user JID.

//    m_discoveryManager->requestItems(channelJid, ns_mix_node_allowed);
//    m_pubSubManager->requestItems(channelJid, ns_mix_node_allowed);

    QXmppMixInvitation invitation;
    invitation.setInviterJid(client()->configuration().jidBare());
    invitation.setInviteeJid(contactJid);
    invitation.setChannelJid(channelJid);
//    invitation.setToken();

    QXmppMessage message;
    message.setTo(contactJid);
    message.setMixInvitation(invitation);

    if (client()->sendPacket(message))
        emit contactInvitedToChannel(channelJid, contactJid);
}

///
/// Renames a channel.
///
/// \param channelJid JID of the channel being renamed
/// \param name new name for the channel
///
void QXmppMixManager::renameChannel(const QString &channelJid, const QString &name)
{
//    QXmppDataForm dataForm;
//    dataForm.setType(QXmppDataForm::Submit);

//    QList<QXmppDataForm::Field> fields;
//    fields.append(QXmppDataForm::Field(QXmppDataForm::Field::HiddenField, QStringLiteral("FORM_TYPE"), ns_mix));
//    fields.append(QXmppDataForm::Field(QXmppDataForm::Field::TextMultiField, QStringLiteral("Name"), name));
//    fields.append(QXmppDataForm::Field(QXmppDataForm::Field::TextMultiField, QStringLiteral("Description")));
//    fields.append(QXmppDataForm::Field(QXmppDataForm::Field::JidSingleField, QStringLiteral("Contact")));

//    dataForm.setFields(fields);

//    QXmppPubSubItem item;
//    // TODO: Use the improved PubSub implementation to pass a data form to setPayload()
//    item.setPayload(dataForm);

//    m_pubSubManager->publishItem(channelJid, ns_mix_node_info, item);
}

void QXmppMixManager::setNick(const QString &channelJid, const QString &requestedNick)
{
    QXmppMixIq iq;
    iq.setType(QXmppIq::Set);
    iq.setTo(channelJid);
    iq.setActionType(QXmppMixIq::SetNick);
    iq.setNick(requestedNick);

    client()->sendPacket(iq);
}

///
/// Requests all nodes of a channel which are accessible by the user.
///
/// \param channelJid JID of the channel containing the nodes.
///
void QXmppMixManager::requestChannelAccessibility(const QString &channelJid) const
{
    requestAccessibleNodes(channelJid);
}

///
/// Transforms a public channel into a private one.
///
/// This cannot be used for channels with server-specified JIDs because they are already private at any time.
///
/// \param channelJid JID of the channel made private
///
void QXmppMixManager::makeChannelPrivate(const QString &channelJid)
{
    m_pubSubChannelRequestsBeingProcessed.insert({makeChannelPrivateAndReturnStanzaId(channelJid), QXmppPubSubIq::QueryType::CreateQuery}, channelJid);
}

///
/// Transforms a private channel into a public one.
///
/// This cannot be used for channels with server-specified JIDs because they will always stay private.
///
/// \param channelJid JID of the channel made public
///
void QXmppMixManager::makeChannelPublic(const QString &channelJid) const
{
    m_pubSubManager->deleteNode(channelJid, ns_mix_node_allowed);
}

///
/// Subscribes for being informed about added and removed member JIDs of a channel.
///
/// \param channelJid JID of the channel for which the member JIDs are observed
///
void QXmppMixManager::subscribeToMemberJids(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_allowed});
}

///
/// Subscribes for being informed about added and removed banned JIDs of a channel.
///
/// \param channelJid JID of the channel for which the banned JIDs are observed
///
void QXmppMixManager::subscribeToBannedJids(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_banned});
}

///
/// Subscribes for being informed about configuration changes.
///
/// \param channelJid JID of the channel for which the configuration changes are observed
///
void QXmppMixManager::subscribeToConfiguration(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_config});
}

/// \param subscribeToConfiguration nothing or true for being informed about configuration changes, otherwise false
/// \param subscribeToInformation nothing or true for being informed about infomration changes, otherwise false
/// \param subscribeToMessages nothing or true for receiving messages which were sent over the channel, otherwise false
/// \param subscribeToParticipants nothing or true for being informed about joined users and left participants, otherwise false
/// \param subscribeToPresences nothing or true for receiving the participants' presence information, otherwise false

///
/// Subscribes for being informed about information changes.
///
/// \param channelJid JID of the channel for which the information changes are observed
///
void QXmppMixManager::subscribeToInformation(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_info});
}

///
/// Subscribes for receiving messages which were sent over the channel.
///
/// \param channelJid JID of the channel from which the messages are received
///
void QXmppMixManager::subscribeToMessages(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_messages});
}

///
/// Subscribes for being informed about joined users and left participants.
///
/// \param channelJid JID of the channel for which the participants are observed
///
void QXmppMixManager::subscribeToParticipants(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_participants});
}

///
/// Subscribes for being informed about the participants' presences.
///
/// \param channelJid JID of the channel for which the participants' presences are observed
///
void QXmppMixManager::subscribeToPresences(const QString &channelJid)
{
    subscribeToNodes(channelJid, {ns_mix_node_presence});
}

///
/// Requests all JIDs which are allowed to join a channel.
///
/// The JIDs can be users (e.g. "alice@example.org") or groups of users (e.g. "example.org") to let all users join which have a JID containing the specified suffix.
/// This is only relevant / used for private channels having a user-specified JID.
///
/// \param channelJid JID of the corresponding channel
///
void QXmppMixManager::requestMemberJids(const QString &channelJid) const
{
    m_pubSubManager->requestItems(channelJid, ns_mix_node_allowed);
}

///
/// Requests all JIDs which are not allowed to join a channel.
///
/// \param channelJid JID of the corresponding channel
///
void QXmppMixManager::requestBannedJids(const QString &channelJid) const
{
    m_pubSubManager->requestItems(channelJid, ns_mix_node_banned);
}

///
/// Requests all participants of a channel.
///
/// In the case of a private channel having a user-specified JID, the participants are a subset of the member JIDs.
///
/// \param channelJid JID of the corresponding channel
///
void QXmppMixManager::requestParticipants(const QString &channelJid) const
{
    m_pubSubManager->requestItems(channelJid, ns_mix_node_participants);
}

void QXmppMixManager::addMemberJid(const QString &channelJid, const QString &jid) const
{
    m_pubSubManager->publishItem(channelJid, ns_mix_node_allowed, QXmppPubSubItem(jid));
}

void QXmppMixManager::removeMemberJid(const QString &channelJid, const QString &jid) const
{
    m_pubSubManager->retractItem(channelJid, ns_mix_node_allowed, jid);
}

void QXmppMixManager::addBannedJid(const QString &channelJid, const QString &jid)
{
    m_pubSubChannelRequestsBeingProcessed.insert({m_pubSubManager->publishItem(channelJid, ns_mix_node_banned, QXmppPubSubItem(jid)), QXmppPubSubIq::QueryType::PublishQuery}, jid);
}

void QXmppMixManager::removeBannedJid(const QString &channelJid, const QString &jid) const
{
    m_pubSubManager->retractItem(channelJid, ns_mix_node_banned, jid);
}

///
/// Deletes a channel.
///
/// \param channelJid JID of the channel being deleted
///
void QXmppMixManager::deleteChannel(const QString &channelJid)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(QXmppUtils::jidToDomain(channelJid));
    iq.setActionType(QXmppMixIq::Destroy);
    iq.setChannelId(QXmppUtils::jidToUser(channelJid));

    client()->sendPacket(iq);
}

void QXmppMixManager::leaveChannel(const QString &channelJid)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(client()->configuration().domain());
    iq.setActionType(QXmppMixIq::ClientLeave);
    iq.setChannelJid(channelJid);

    // Cache the request to retrieve the channel JID for emitting a corresponding signal.
    m_requestsBeingProcessed.insert(iq.id(), channelJid);

    client()->sendPacket(iq);
}

bool QXmppMixManager::handleStanza(const QDomElement &element)
{
    if (element.tagName() == "iq") {
        QString channelJid;

        if (QXmppMixIq::isMixIq(element)) {
            QXmppMixIq iq;
            iq.parse(element);

            // default value for the channel JID which is overwritten by more specific cases
            channelJid = iq.from();

            if (iq.channelJid().isEmpty()) {
                QXmppRosterManager *rosterManager;
                rosterManager = client()->findExtension<QXmppRosterManager>();

                if (rosterManager)
                    iq.setChannelJid(rosterManager->rosterEntryByMixParticipantId(iq.participantId()).bareJid());

                if (iq.channelJid().isEmpty())
                    iq.setChannelJid(iq.channelId() % "@" % iq.from());
            }

            switch (iq.type()) {
            case QXmppIq::Result:
                switch (iq.actionType()) {
                case QXmppMixIq::Create: {
//                    channelJid = m_requestsBeingProcessed.take(iq.id());
//                    // If the channel ID was not set by the user and therefore the request not cached, the channel JID is set by the server and taken from the stanza for emitting a successful creation.
//                    // Otherwise, the channel JID is taken from the cached request and the "Allowed" node for that channel JID is created because the channel was intended to be not public.
//                    if (channelJid.isEmpty())
//                        emit channelCreated(iq.channelJid());
//                    else
//                        m_pubSubRequestsBeingProcessed.insert({makeChannelPrivateAndReturnStanzaId(channelJid), QXmppPubSubIq::QueryType::CreateQuery}, channelJid);

                    // If the channel was intended to be public, directly emit a signal for the successful channel creation.
                    // Otherwise, the channel is made private and the signal is emitted afterwards.
                    if (m_requestsBeingProcessed.take(iq.id()).isEmpty())
                        emit channelCreated(iq.channelJid());
                    else
                        m_pubSubChannelRequestsBeingProcessed.insert({makeChannelPrivateAndReturnStanzaId(iq.channelJid()), QXmppPubSubIq::QueryType::CreateQuery}, iq.channelJid());

                    return true;
                case QXmppMixIq::ClientJoin:
                    channelJid = m_requestsBeingProcessed.take(iq.id());
                    if (!channelJid.isEmpty()) {
                        emit channelJoined(channelJid, iq.nodesBeingSubscribed());
                        return true;
                    }
                    return false;
                case QXmppMixIq::ClientLeave:
                    channelJid = m_requestsBeingProcessed.take(iq.id());
                    if (!channelJid.isEmpty()) {
                        emit channelLeft(channelJid);
                        return true;
                    }
                    return false;
                case QXmppMixIq::UpdateSubscription:
                    for (const QString node : iq.nodesBeingSubscribed()) {
                        if (node == ns_mix_node_allowed)
                            emit subscribedToMemberJids(channelJid);
                        else if (node == ns_mix_node_banned)
                            emit subscribedToBannedJids(channelJid);
                        else if (node == ns_mix_node_config)
                            emit subscribedToConfiguration(channelJid);
                        else if (node == ns_mix_node_info)
                            emit subscribedToInformation(channelJid);
                        else if (node == ns_mix_node_messages)
                            emit subscribedToMessages(channelJid);
                        else if (node == ns_mix_node_participants)
                            emit subscribedToParticipants(channelJid);
                        else if (node == ns_mix_node_presence)
                            emit subscribedToPresences(channelJid);
                    }

                    for (const QString node : iq.nodesBeingUnsubscribed()) {
                        if (node == ns_mix_node_allowed)
                            emit unsubscribedFromMemberJids(channelJid);
                        else if (node == ns_mix_node_banned)
                            emit unsubscribedFromBannedJids(channelJid);
                        else if (node == ns_mix_node_config)
                            emit unsubscribedFromConfiguration(channelJid);
                        else if (node == ns_mix_node_info)
                            emit unsubscribedFromInformation(channelJid);
                        else if (node == ns_mix_node_messages)
                            emit unsubscribedFromMessages(channelJid);
                        else if (node == ns_mix_node_participants)
                            emit unsubscribedFromParticipants(channelJid);
                        else if (node == ns_mix_node_presence)
                            emit unsubscribedFromPresences(channelJid);
                    }

                    return true;
                case QXmppMixIq::SetNick:
                    emit nickChanged(channelJid, iq.nick());
                    return true;
        //            case QXmppMixIq::Destroy:
        //              channelJid = m_requestsBeingProcessed.take(iq.id());
        //                if (!channelJid.isEmpty()) {
        //                    emit channelDeleted(channelJid);
        //                    return true;
        //                }
        //                return false;
                }
                default:
                    return false;
                }

            case QXmppIq::Error:
                switch (iq.actionType()) {
                case QXmppMixIq::Create:
                    channelJid = iq.channelJid();
                    if (!channelJid.isEmpty()) {
                        warning(QStringLiteral("Creating the MIX channel %1 failed: ").arg(channelJid).append(iq.error().text()));
                        emit channelCreationFailed(channelJid, iq.error());
                        return true;
                    }
                    return false;
                case QXmppMixIq::ClientJoin:
                    channelJid = m_requestsBeingProcessed.take(iq.id());
                    if (!channelJid.isEmpty()) {
                        warning(QStringLiteral("Joining the MIX channel %1 failed: ").arg(channelJid).append(iq.error().text()));
                        emit channelJoiningFailed(channelJid, iq.error());
                        return true;
                    }
                    return false;
                case QXmppMixIq::Destroy:
                    channelJid = iq.channelJid();
                    if (!channelJid.isEmpty()) {
                        warning(QStringLiteral("Deleting the MIX channel %1 failed: ").arg(channelJid).append(iq.error().text()));
                        emit channelDeletionFailed(channelJid, iq.error());
                        return true;
                    }
                    return false;
                default:
                    return false;
                }

            default:
                return false;
            }
        } else {
            QXmppIq iq;
            iq.parse(element);

            if (iq.type() == QXmppIq::Result) {
                channelJid = m_pubSubChannelRequestsBeingProcessed.take({iq.id(), QXmppPubSubIq::QueryType::CreateQuery});

                // If the channel was already created as a public one before but needed to be made private, it is now announced as created.
                if (!channelJid.isEmpty()) {
                    emit channelCreated(channelJid);
                    return true;
                }

                QString bannedJid = m_pubSubNodeRequestsBeingProcessed.take({iq.id(), QXmppPubSubIq::QueryType::CreateQuery});

                // If the JID could not be added to the banned JIDs because the corresponding node did not exist, the JID is added to it now.
                if (!bannedJid.isEmpty()) {
                    addBannedJid(iq.from(), bannedJid);
                    return true;
                }

                return false;
            } else if (iq.type() == QXmppIq::Error) {
                QString bannedJid = m_pubSubChannelRequestsBeingProcessed.take({iq.id(), QXmppPubSubIq::QueryType::PublishQuery});

                // If the JID could not be added to the banned JIDs because the corresponding node did not exist, the node is created now.
                if (!bannedJid.isEmpty()) {
                    m_pubSubNodeRequestsBeingProcessed.insert({m_pubSubManager->createNode(iq.from(), ns_mix_node_banned), QXmppPubSubIq::QueryType::CreateQuery}, bannedJid);
                    return true;
                }

                return false;
            }

            return false;
        }
    } else if (element.tagName() == "message") {
        QXmppMessage message;
        message.parse(element);

        if (message.isMixInvitation()) {
            QXmppMixInvitation invitation = message.mixInvitation();
            emit invitedToChannel(invitation.channelJid(), invitation.inviterJid());
        }
    }

    return false;
}

void QXmppMixManager::setClient(QXmppClient *client)
{
    QXmppClientExtension::setClient(client);

    if (!(m_discoveryManager = client->findExtension<QXmppDiscoveryManager>()))
        client->addExtension(m_discoveryManager = new QXmppDiscoveryManager);

    // Check all incoming information about and items of entities.
    connect(m_discoveryManager, &QXmppDiscoveryManager::infoReceived, this, &QXmppMixManager::handleDiscoInfo);
    connect(m_discoveryManager, &QXmppDiscoveryManager::itemsReceived, this, &QXmppMixManager::handleDiscoItems);

    // Remove all mix services after the client disconnected from the server.
    connect(client, &QXmppClient::disconnected, [this] () {
        setIsSupportedByServer(false);
        setIsArchivingSupportedByServer(false);
        m_services.clear();
    });

    if (!(m_pubSubManager = client->findExtension<QXmppPubSubManager>()))
        client->addExtension(m_pubSubManager = new QXmppPubSubManager);

    connect(m_pubSubManager, &QXmppPubSubManager::itemsReceived, this, &QXmppMixManager::handlePubSubItems);
    connect(m_pubSubManager, &QXmppPubSubManager::eventNotificationReceived, this, &QXmppMixManager::handleEventNotification);
}

void QXmppMixManager::handleDiscoInfo(const QXmppDiscoveryIq &iq)
{
    // Check the server's functionality to support MIX clients.
    if (iq.from().isEmpty() || iq.from() == client()->configuration().domain()) {
        // Check whether MIX is supported.
        if (iq.features().contains(ns_mix_pam)) {
            setIsSupportedByServer(true);

            // Check whether MIX archiving is supported.
            if (iq.features().contains(ns_mix_pam_archiving))
                setIsArchivingSupportedByServer(true);
        }
    }

    // Check the MIX service's functionality.
    if (!iq.features().contains(ns_mix))
        return;
    for (const QXmppDiscoveryIq::Identity &identity : iq.identities()) {
        // Type "text" is a workaround for older ejabberd versions.
        // TODO: Delete ' || identity.type() == "text"' after ejabberd update
        if (identity.category() == "conference" && (identity.type() == "mix" || identity.type() == "text")) {
            QXmppMixService service;
            service.setJid(iq.from().isEmpty() ? client()->configuration().domain() : iq.from());
            service.setSearchable(iq.features().contains(ns_mix_searchable));
            service.setCanCreateChannel(iq.features().contains(ns_mix_create_channel));

            if (!m_services.contains(service)) {
                m_services.append(service);
                emit serviceDiscovered(service);
            }

            return;
        }
    }

    //    for (const QXmppDiscoveryIq::Item &item : iq.items())
}

void QXmppMixManager::handleDiscoItems(const QXmppDiscoveryIq &iq)
{
    if (iq.queryNode() == "mix") {
        QStringList accessibleNodes;

        for (const QXmppDiscoveryIq::Item &item : iq.items())
            accessibleNodes.append(item.node());

        if (accessibleNodes.contains(ns_mix_node_allowed))
            emit channelAccessibilityReceived(iq.from(), false);
        else
            emit channelAccessibilityReceived(iq.from(), true);
    }
}

void QXmppMixManager::handlePubSubItems(const QXmppPubSubIq &iq)
{
    QString channelJid = iq.from();

    if (iq.queryNodeName() == ns_mix_node_allowed) {
        for (const QXmppPubSubItem &pubSubItem : iq.items())
            emit memberJidReceived(channelJid, pubSubItem.id());
    } else if (iq.queryNodeName() == ns_mix_node_banned) {
        for (const QXmppPubSubItem &pubSubItem : iq.items())
            emit bannedJidReceived(channelJid, pubSubItem.id());
    } else if (iq.queryNodeName() == ns_mix_node_participants) {
        for (const QXmppPubSubItem &pubSubItem : iq.items()) {
            if (QXmppMixParticipantItem::isMixParticipantItem(pubSubItem))
                emit participantReceived(channelJid, QXmppMixParticipantItem(pubSubItem));
        }
    }
}

void QXmppMixManager::handleEventNotification(const QXmppMessage &message)
{
    QString channelJid = message.from();
    QXmppPubSubEvent event = message.pubSubEvent();

    if (event.nodeName() == ns_mix_node_participants) {
        switch (event.type()) {
        // TODO: Specify standard PubSub behavior for deleted channels (nodes) in MIX XEP
        case QXmppPubSubIq::QueryType::DeleteQuery:
            emit channelDeleted(channelJid);
            return;
        case QXmppPubSubIq::QueryType::ItemsQuery:
            for (QXmppPubSubItem pubSubItem : event.items()) {
                switch (pubSubItem.type()) {
                case QXmppPubSubItem::Item:
                    if (QXmppMixParticipantItem::isMixParticipantItem(pubSubItem))
                        emit userJoinedOrParticipantModified(channelJid, QXmppMixParticipantItem(pubSubItem));
                    return;
                case QXmppPubSubItem::Retract:
                    emit participantLeft(channelJid, pubSubItem.id());
                    return;
                }
            }
            break;
        default:
            return;
        }
    } else if (event.nodeName() == ns_mix_node_allowed) {
        switch (event.type()) {
        // TODO: That information must be retrieved from an update of the Config node (update of <field var='Nodes Present'>) but that node is optional so that it cannot be ensured that users are always informed about a new Allowed node
//        case QXmppPubSubIq::QueryType::CreateQuery:
//            emit channelMadePrivate(channelJid);

//            return;
        case QXmppPubSubIq::QueryType::DeleteQuery:
            emit channelMadePublic(channelJid);
            return;
        case QXmppPubSubIq::QueryType::ItemsQuery:
            for (QXmppPubSubItem pubSubItem : event.items()) {
                QString memberJid = pubSubItem.id();

                switch (pubSubItem.type()) {
                case QXmppPubSubItem::Item:
                    emit memberJidAdded(channelJid, memberJid);
                    return;
                case QXmppPubSubItem::Retract:
                    emit memberJidRemoved(channelJid, memberJid);
//                    removeParticipant(channelJid, memberJid);
                    // TODO: It would be better if the XEP would specify that when a JID is removed from the Allowed node, it will automatically be removed from the Participants node
//                    addBannedJid(channelJid, memberJid);
                    return;
                }
            }
            break;
        default:
            return;
        }
    } else if (event.nodeName() == ns_mix_node_banned && event.type() == QXmppPubSubIq::QueryType::ItemsQuery) {
        for (QXmppPubSubItem pubSubItem : event.items()) {
            QString bannedJid = pubSubItem.id();

            switch (pubSubItem.type()) {
            case QXmppPubSubItem::Item:
                emit bannedJidAdded(channelJid, bannedJid);
                return;
            case QXmppPubSubItem::Retract:
                emit bannedJidRemoved(channelJid, bannedJid);
                return;
            }
        }
    }
}

///
/// Transforms a public channel into a private one.
///
/// \param channelJid JID of the channel made private
///
/// \return the ID of the sent IQ stanza
///
QString QXmppMixManager::makeChannelPrivateAndReturnStanzaId(const QString &channelJid) const
{
    return m_pubSubManager->createNode(channelJid, ns_mix_node_allowed);
}

void QXmppMixManager::requestAccessibleNodes(const QString &channelJid) const
{
    m_discoveryManager->requestItems(channelJid, "mix");
}

///
/// Subscribes to nodes of a channel.
///
/// \param channelJid JID of the channel with the passed nodes
/// \param nodes nodes to subscribe to
///
void QXmppMixManager::subscribeToNodes(const QString &channelJid, const QStringList &nodes)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(channelJid);
    iq.setActionType(QXmppMixIq::UpdateSubscription);
    iq.setNodesBeingSubscribed(nodes);

    client()->sendPacket(iq);
}

///
/// Unsubscribes from nodes of a channel.
///
/// \param channelJid JID of the channel with the passed nodes
/// \param nodes nodes to subscribe to
///
void QXmppMixManager::unsubscribeFromNodes(const QString &channelJid, const QStringList &nodes)
{
    QXmppMixIq iq;

    iq.setType(QXmppIq::Set);
    iq.setTo(channelJid);
    iq.setActionType(QXmppMixIq::UpdateSubscription);
    iq.setNodesBeingUnsubscribed(nodes);

    client()->sendPacket(iq);
}

//void QXmppMixManager::removeParticipant(const QString &channelJid, const QString &participantJid)
//{
//    m_pubSubManager->retractItem(channelJid, ns_mix_node_participants, participantJid);
//}

void QXmppMixManager::setIsSupportedByServer(bool isSupportedByServer)
{
    if (m_isSupportedByServer != isSupportedByServer) {
        m_isSupportedByServer = isSupportedByServer;
        emit isSupportedByServerChanged(m_isSupportedByServer);
    }
}

void QXmppMixManager::setIsArchivingSupportedByServer(bool isArchivingSupportedByServer)
{
    if (m_isArchivingSupportedByServer != isArchivingSupportedByServer) {
        m_isArchivingSupportedByServer = isArchivingSupportedByServer;
        emit isArchivingSupportedByServerChanged(m_isArchivingSupportedByServer);
    }
}
