/*
 * Copyright (C) 2008-2021 The QXmpp developers
 *
 * Author:
 *  Melvin Keskin
 *
 * Source:
 *  https://github.com/qxmpp-project/qxmpp
 *
 * This file is a part of QXmpp library.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 */

#include "QXmppMixInvitation.h"

#include "QXmppConstants_p.h"

#include <QDomElement>
#include <QSharedData>

class QXmppMixInvitationPrivate : public QSharedData
{
public:
    QString inviterJid;
    QString inviteeJid;
    QString channelJid;
    QString token;
};

QXmppMixInvitation::QXmppMixInvitation()
    : d(new QXmppMixInvitationPrivate)
{
}

QXmppMixInvitation::QXmppMixInvitation(const QXmppMixInvitation &other) = default;

QXmppMixInvitation &QXmppMixInvitation::operator=(const QXmppMixInvitation &other) = default;

QXmppMixInvitation::~QXmppMixInvitation() = default;

///
/// Returns the JID of the inviter.
///
QString QXmppMixInvitation::inviterJid() const
{
    return d->inviterJid;
}

///
/// Sets the JID of the inviter.
///
/// \param inviterJid inviter's JID
///
void QXmppMixInvitation::setInviterJid(const QString &inviterJid)
{
    d->inviterJid = inviterJid;
}

///
/// Returns the JID of the invitee.
///
QString QXmppMixInvitation::inviteeJid() const
{
    return d->inviteeJid;
}

///
/// Sets the JID of the invitee.
///
/// \param inviteeJid invitee's JID
///
void QXmppMixInvitation::setInviteeJid(const QString &inviteeJid)
{
    d->inviteeJid = inviteeJid;
}

///
/// Returns the JID of the channel.
///
QString QXmppMixInvitation::channelJid() const
{
    return d->channelJid;
}

///
/// Sets the JID of the channel.
///
/// \param channelJid channel JID
///
void QXmppMixInvitation::setChannelJid(const QString &channelJid)
{
    d->channelJid = channelJid;
}

///
/// Returns the token which is generated by the server and used by the invitee for authentication.
///
QString QXmppMixInvitation::token() const
{
    return d->token;
}

///
/// Sets the token which is generated by the server and used by the invitee for authentication.
///
/// \param token authentication token
///
void QXmppMixInvitation::setToken(const QString &token)
{
    d->token = token;
}

///
/// Determines whether the invitation object is initialized.
///
/// \return true if all of the object's attributes are empty
///
bool QXmppMixInvitation::isNull() const
{
    return d->inviterJid.isEmpty() && d->inviteeJid.isEmpty() && d->channelJid.isEmpty() && d->token.isEmpty();
}

void QXmppMixInvitation::parse(const QXmppElement &element)
{
    d->inviterJid = element.firstChildElement(QStringLiteral("inviter")).value();
    d->inviteeJid = element.firstChildElement(QStringLiteral("invitee")).value();
    d->channelJid = element.firstChildElement(QStringLiteral("channel")).value();
    d->token = element.firstChildElement(QStringLiteral("token")).value();
}

QXmppElement QXmppMixInvitation::toElement() const
{
    QXmppElement element;
    element.setTagName(QStringLiteral("invitation"));
    element.setAttribute(QStringLiteral("xmlns"), ns_mix_misc);

    QXmppElement inviterJid;
    inviterJid.setTagName(QStringLiteral("inviter"));
    inviterJid.setValue(d->inviterJid);
    element.appendChild(inviterJid);

    QXmppElement inviteeJid;
    inviteeJid.setTagName(QStringLiteral("invitee"));
    inviteeJid.setValue(d->inviteeJid);
    element.appendChild(inviteeJid);

    QXmppElement channelJid;
    channelJid.setTagName(QStringLiteral("channel"));
    channelJid.setValue(d->channelJid);
    element.appendChild(channelJid);

    QXmppElement token;
    token.setTagName(QStringLiteral("token"));
    token.setValue(d->token);
    element.appendChild(token);

    return element;
}

///
/// Returns true if the given DOM element is a MIX invitation.
///
bool QXmppMixInvitation::isMixInvitation(const QDomElement &element)
{
    return element.tagName() == QStringLiteral("invitation") && (element.namespaceURI().isEmpty() || element.namespaceURI() == ns_mix_misc);
}
